// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYdasw5LZpkLrWuLB4xcC2OIzYvnst-g',
    appId: '1:466989792222:web:0965ee00f2e9eb0902fb4f',
    messagingSenderId: '466989792222',
    projectId: 'ecoquest-42112',
    authDomain: 'ecoquest-42112.firebaseapp.com',
    storageBucket: 'ecoquest-42112.firebasestorage.app',
    measurementId: 'G-J7TSGHXKRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFiSfWU18T26zV5ixCelbrcVHC0o7fobs',
    appId: '1:466989792222:android:71b80f6f199b4db102fb4f',
    messagingSenderId: '466989792222',
    projectId: 'ecoquest-42112',
    storageBucket: 'ecoquest-42112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgn66H87QXG0eJBXPd_sJJ_079gQ7ar7E',
    appId: '1:466989792222:ios:0e37bd625528629202fb4f',
    messagingSenderId: '466989792222',
    projectId: 'ecoquest-42112',
    storageBucket: 'ecoquest-42112.firebasestorage.app',
    iosBundleId: 'com.example.ecoquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgn66H87QXG0eJBXPd_sJJ_079gQ7ar7E',
    appId: '1:466989792222:ios:0e37bd625528629202fb4f',
    messagingSenderId: '466989792222',
    projectId: 'ecoquest-42112',
    storageBucket: 'ecoquest-42112.firebasestorage.app',
    iosBundleId: 'com.example.ecoquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYdasw5LZpkLrWuLB4xcC2OIzYvnst-g',
    appId: '1:466989792222:web:9bf5f24c9d1d8c0202fb4f',
    messagingSenderId: '466989792222',
    projectId: 'ecoquest-42112',
    authDomain: 'ecoquest-42112.firebaseapp.com',
    storageBucket: 'ecoquest-42112.firebasestorage.app',
    measurementId: 'G-DEEZ011E4G',
  );
}
